fix: 更新测试脚本

diff --git a/test/run_test b/test/run_test
--- a/test/run_test
+++ b/test/run_test
@@ -1,28 +1,27 @@
 #!/bin/sh
 
-if [ ! -f ../parser || ! -f ../parser2 ]
-  then echo "Need to build parser first";
-  exit 1;
+if [ ! -f ../parser ]
+  then echo "Need to build parser first"; exit 1;
 fi
 
 for i in input*
-  do
-    if [ ! -f "out.$i" ] then
-      echo "Can't run test on $i, no input file"
-    else
-      echo -n $i
-      ../parser $i
-      cc -o out out.s
-      ./out > trial.$i
-      cmp -s "out.$i" "trial.$i"
-
-      if [ "$?" -eq "1" ] then
-        echo ": Failed"
-        diff -c "out.$i" "trial.$i"
-        echo
+  do if [ ! -f "out.$i" ]
+      then echo "Can't run test on $i, no input file"
       else
-        echo ": Ok"
+        echo -n $i
+        ../parser $i
+        cc -o out out.s
+        ./out > trial.$i
+        cmp -s "out.$i" "trial.$i"
+
+        if [ "$?" -eq "1" ]
+        then
+          echo ": Failed"
+          diff -c "out.$i" "trial.$i"
+          echo
+        else
+          echo ": Ok"
+        fi
+        rm -rf out out.s "trial.$i"
       fi
-      rm -rf out out.s "trial.$i"
-    fi
   done
